2023-05-20,15:53:27.162086200, Exception:Database could not be called ,was thrown
se.kth.iv1350.amazingpos.integration.ExternalInvetoryInventoryException: Database could not be called
	at se.kth.iv1350.amazingpos.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:27)
	at se.kth.iv1350.amazingpos.model.ItemManager.geItem(ItemManager.java:28)
	at se.kth.iv1350.amazingpos.controller.Controller.scanItem(Controller.java:62)
	at se.kth.iv1350.amazingpos.view.View.runFakeExecution(View.java:50)
	at se.kth.iv1350.amazingpos.startup.Main.main(Main.java:21)


2023-05-20,15:55:06.928304900, Exception:Database could not be called ,was thrown
se.kth.iv1350.amazingpos.integration.ExternalInvetoryInventoryException: Database could not be called
	at se.kth.iv1350.amazingpos.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:27)
	at se.kth.iv1350.amazingpos.model.ItemManager.geItem(ItemManager.java:28)
	at se.kth.iv1350.amazingpos.controller.Controller.scanItem(Controller.java:62)
	at se.kth.iv1350.amazingpos.view.View.runFakeExecution(View.java:53)
	at se.kth.iv1350.amazingpos.startup.Main.main(Main.java:21)


2023-05-20,15:55:32.489084300, Exception:Database could not be called ,was thrown
se.kth.iv1350.amazingpos.integration.ExternalInvetoryInventoryException: Database could not be called
	at se.kth.iv1350.amazingpos.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:27)
	at se.kth.iv1350.amazingpos.model.ItemManager.geItem(ItemManager.java:28)
	at se.kth.iv1350.amazingpos.controller.Controller.scanItem(Controller.java:62)
	at se.kth.iv1350.amazingpos.view.View.runFakeExecution(View.java:54)
	at se.kth.iv1350.amazingpos.startup.Main.main(Main.java:21)


2023-05-20,15:57:04.627275700, Exception:Database could not be called ,was thrown
se.kth.iv1350.amazingpos.integration.ExternalInvetoryInventoryException: Database could not be called
	at se.kth.iv1350.amazingpos.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:27)
	at se.kth.iv1350.amazingpos.model.ItemManager.geItem(ItemManager.java:28)
	at se.kth.iv1350.amazingpos.controller.Controller.scanItem(Controller.java:62)
	at se.kth.iv1350.amazingpos.view.View.runFakeExecution(View.java:55)
	at se.kth.iv1350.amazingpos.startup.Main.main(Main.java:21)


2023-05-20,15:57:20.155740, Exception:Database could not be called ,was thrown
se.kth.iv1350.amazingpos.integration.ExternalInvetoryInventoryException: Database could not be called
	at se.kth.iv1350.amazingpos.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:27)
	at se.kth.iv1350.amazingpos.model.ItemManager.geItem(ItemManager.java:28)
	at se.kth.iv1350.amazingpos.controller.Controller.scanItem(Controller.java:62)
	at se.kth.iv1350.amazingpos.view.View.runFakeExecution(View.java:55)
	at se.kth.iv1350.amazingpos.startup.Main.main(Main.java:21)


2023-05-20,15:58:42.905528200, Exception:Database could not be called ,was thrown
se.kth.iv1350.amazingpos.integration.ExternalInvetoryInventoryException: Database could not be called
	at se.kth.iv1350.amazingpos.integration.ExternalInventorySystem.getItemDescription(ExternalInventorySystem.java:27)
	at se.kth.iv1350.amazingpos.model.ItemManager.geItem(ItemManager.java:28)
	at se.kth.iv1350.amazingpos.controller.Controller.scanItem(Controller.java:62)
	at se.kth.iv1350.amazingpos.view.View.runFakeExecution(View.java:55)
	at se.kth.iv1350.amazingpos.startup.Main.main(Main.java:21)


